# Generated by Django 3.2.23 on 2024-01-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='tag name')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='relation',
            field=models.ManyToManyField(blank=True, null=True, related_name='_pages_blog_relation_+', to='pages.Blog', verbose_name='relation'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='pages.Tag', verbose_name='tag'),
        ),
    ]
